<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('APPS:admin.library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		//TODO do something before all the action
	}
	
	public function run() {
		list($groupType) = $this->getInput(array('type'), 'get');
		$groupType or $groupType = 'member';
		$groups = $this->_getGroupDs()->getGroupsByTypeInUpgradeOrder($groupType);
		$groupTypes = $this->_getGroupDs()->getGroupTypes();

		$groupInfo = $this->_getGroupDs()->getGroupsByType($groupType);
		$gids = array();
		foreach($groupInfo as $v){
			$gids[] = intval($v['gid']);
		}

		$configByGids = $this->_getAppEncryptPostsConfigService()->getConfigByGids($gids);
		$configInfo = array();
		foreach($configByGids as $key => $value){
			$configInfo[$key] = $value;
		}

		$typeClasses = array();
		foreach ($groupTypes as $v){
			$typeClasses[$v] = $groupType == $v ? ' class="current"' : '';//TODO
		}

		$this->setOutput($typeClasses, 'typeClasses');
		$this->setOutput($configInfo, 'configInfo');
		$this->setOutput($groupType, 'groupType');
		$this->setOutput($groups, 'groups');


	}

	public function doSetAction(){
		$config = $this->getInput('conf', 'post');
		if(!is_array($config)) 
			$this->showError('非法操作');
		$config = array_map('intval', $config);
		$this->_getAppEncryptPostsConfigService()->setConfig($config);
		$this->showMessage('设置成功');
	}


	private function _getAppEncryptPostsConfigService(){
		return Wekit::load('EXT:encryptposts.service.srv.App_EncryptPosts_ConfigDo');
	}

	private function _getGroupDs(){
		return Wekit::load('usergroup.PwUserGroups');
	}


}

?>